language: python

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.4"

env:
  global:
    - DEBUG=0

install:
  - make install

before_script:
  - psql -c "CREATE DATABASE test_politize_recommendation;" -U postgres

script:
  - make lint
  - make test

cache:
  - pip

after_success:
  - codecov
